//Catched binary at 0085F908 of size 6944 bytes!
//Parsing...

pixelshader pshaderMask =
asm {
    ps_1_1
    tex t0
    add_sat r0, t0, c0
    mul r0, r0, v0

// approximately 3 instruction slots used (1 texture, 2 arithmetic)
};

pixelshader pshaderFlash =
asm {
    ps_1_1
    tex t0
    lrp r0.xyz, c0.w, c0, t0
  + mov r0.w, t0.w
    mul r0, r0, v0

// approximately 3 instruction slots used (1 texture, 2 arithmetic)
};

pixelshader pshaderDP =
asm {
    ps_1_1
    tex t0
    dp3 r0.xyz, t0, c0
  + mov r0.w, t0.w
    mul r0, r0, v0

// approximately 3 instruction slots used (1 texture, 2 arithmetic)
};

pixelshader pshaderDPFlash =
asm {
    ps_1_1
    tex t0
    dp3 r0.xyz, t0, c0
    lrp r0.xyz, c1.w, c1, r0
  + mov r0.w, t0.w
    mul r0, r0, v0

// approximately 4 instruction slots used (1 texture, 3 arithmetic)
};

pixelshader pshaderEx0 =
asm {
    ps_1_1
    def c1, 0.25999999, -1, 0.25999999, 0
    tex t0
    tex t1
    dp3 r0, t0, c1
    cnd r0, r0.w, t1, t0
    mul r0, r0, v0

// approximately 5 instruction slots used (2 texture, 3 arithmetic)
};

pixelshader pshaderEx0Mask =
asm {
    ps_1_1
    def c1, 0.25999999, -1, 0.25999999, 0
    tex t0
    tex t1
    dp3 r0, t0, c1
    cnd r0, r0.w, t1, t0
    mul r0, r0, v0
    add_sat r0, r0, c0
    mul r0, r0, v0

// approximately 7 instruction slots used (2 texture, 5 arithmetic)
};

pixelshader pshaderEx0DP =
asm {
    ps_1_1
    def c1, 0.25999999, -1, 0.25999999, 0
    tex t0
    tex t1
    dp3 r0, t0, c1
    cnd r0, r0.w, t1, t0
    mul r0, r0, v0
    dp3 r1.xyz, r0, c0
  + mov r1.w, r0.w
    mul r0, r1, v0

// approximately 7 instruction slots used (2 texture, 5 arithmetic)
};


//listing of all techniques and passes with embedded asm listings

technique SampleTexhnique
{
    pass P0
    {
        //No embedded vertex shader
        pixelshader =
            asm {
                ps_1_1
                tex t0
                add_sat r0, t0, c0
                mul r0, r0, v0

            // approximately 3 instruction slots used (1 texture, 2 arithmetic)
            };
    }
    pass P1
    {
        //No embedded vertex shader
        pixelshader =
            asm {
                ps_1_1
                tex t0
                lrp r0.xyz, c0.w, c0, t0
              + mov r0.w, t0.w
                mul r0, r0, v0

            // approximately 3 instruction slots used (1 texture, 2 arithmetic)
            };
    }
    pass P2
    {
        //No embedded vertex shader
        pixelshader =
            asm {
                ps_1_1
                tex t0
                dp3 r0.xyz, t0, c0
              + mov r0.w, t0.w
                mul r0, r0, v0

            // approximately 3 instruction slots used (1 texture, 2 arithmetic)
            };
    }
    pass P3
    {
        //No embedded vertex shader
        pixelshader =
            asm {
                ps_1_1
                tex t0
                dp3 r0.xyz, t0, c0
                lrp r0.xyz, c1.w, c1, r0
              + mov r0.w, t0.w
                mul r0, r0, v0

            // approximately 4 instruction slots used (1 texture, 3 arithmetic)
            };
    }
    pass P4
    {
        vertexshader =
            asm {
            //
            // Generated by Microsoft (R) D3DX9 Shader Compiler
            //
            // Parameters:
            //
            //   float x;
            //   float y;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   x            c0       1
            //   y            c1       1
            //

                preshader
                mul c0.x, c0.x, (0.00390625)
                mul c1.x, c1.x, (0.00390625)

            // approximately 2 instructions used
            //
            // Generated by Microsoft (R) D3DX9 Shader Compiler
            //
            // Parameters:
            //
            //   float height;
            //   float width;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   width        c2       1
            //   height       c3       1
            //

                vs_1_1
                def c4, 0.00390625, 0, -1, 1
                def c5, 0.00312500005, -0.00416666688, 1, 0
                dcl_position v0
                dcl_color v1
                dcl_texcoord v2
                mul r0.x, v2.x, c2.x
                mov r1, c4
                mad oT1.x, r0.x, r1.x, c0.x
                mul r0.x, v2.y, c3.x
                mad oT1.y, r0.x, r1.x, c1.x
                mad oPos, v0, c5.xyzz, r1.zwyy
                mov oD0, v1
                mov oT0.xy, v2

            // approximately 8 instruction slots used
            };

        pixelshader =
            asm {
                ps_1_1
                def c1, 0.25999999, -1, 0.25999999, 0
                tex t0
                tex t1
                dp3 r0, t0, c1
                cnd r0, r0.w, t1, t0
                mul r0, r0, v0

            // approximately 5 instruction slots used (2 texture, 3 arithmetic)
            };
    }
    pass P5
    {
        vertexshader =
            asm {
            //
            // Generated by Microsoft (R) D3DX9 Shader Compiler
            //
            // Parameters:
            //
            //   float x;
            //   float y;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   x            c0       1
            //   y            c1       1
            //

                preshader
                mul c0.x, c0.x, (0.00390625)
                mul c1.x, c1.x, (0.00390625)

            // approximately 2 instructions used
            //
            // Generated by Microsoft (R) D3DX9 Shader Compiler
            //
            // Parameters:
            //
            //   float height;
            //   float width;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   width        c2       1
            //   height       c3       1
            //

                vs_1_1
                def c4, 0.00390625, 0, -1, 1
                def c5, 0.00312500005, -0.00416666688, 1, 0
                dcl_position v0
                dcl_color v1
                dcl_texcoord v2
                mul r0.x, v2.x, c2.x
                mov r1, c4
                mad oT1.x, r0.x, r1.x, c0.x
                mul r0.x, v2.y, c3.x
                mad oT1.y, r0.x, r1.x, c1.x
                mad oPos, v0, c5.xyzz, r1.zwyy
                mov oD0, v1
                mov oT0.xy, v2

            // approximately 8 instruction slots used
            };

        pixelshader =
            asm {
                ps_1_1
                def c1, 0.25999999, -1, 0.25999999, 0
                tex t0
                tex t1
                dp3 r0, t0, c1
                cnd r0, r0.w, t1, t0
                mul r0, r0, v0
                add_sat r0, r0, c0
                mul r0, r0, v0

            // approximately 7 instruction slots used (2 texture, 5 arithmetic)
            };
    }
    pass P6
    {
        vertexshader =
            asm {
            //
            // Generated by Microsoft (R) D3DX9 Shader Compiler
            //
            // Parameters:
            //
            //   float x;
            //   float y;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   x            c0       1
            //   y            c1       1
            //

                preshader
                mul c0.x, c0.x, (0.00390625)
                mul c1.x, c1.x, (0.00390625)

            // approximately 2 instructions used
            //
            // Generated by Microsoft (R) D3DX9 Shader Compiler
            //
            // Parameters:
            //
            //   float height;
            //   float width;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   width        c2       1
            //   height       c3       1
            //

                vs_1_1
                def c4, 0.00390625, 0, -1, 1
                def c5, 0.00312500005, -0.00416666688, 1, 0
                dcl_position v0
                dcl_color v1
                dcl_texcoord v2
                mul r0.x, v2.x, c2.x
                mov r1, c4
                mad oT1.x, r0.x, r1.x, c0.x
                mul r0.x, v2.y, c3.x
                mad oT1.y, r0.x, r1.x, c1.x
                mad oPos, v0, c5.xyzz, r1.zwyy
                mov oD0, v1
                mov oT0.xy, v2

            // approximately 8 instruction slots used
            };

        pixelshader =
            asm {
                ps_1_1
                def c1, 0.25999999, -1, 0.25999999, 0
                tex t0
                tex t1
                dp3 r0, t0, c1
                cnd r0, r0.w, t1, t0
                mul r0, r0, v0
                dp3 r1.xyz, r0, c0
              + mov r1.w, r0.w
                mul r0, r1, v0

            // approximately 7 instruction slots used (2 texture, 5 arithmetic)
            };
    }
}
